name: Publish Docker image to GitHub Packages

on:
  push:
    branches:
      - master  # 或者您想要触发构建的任何分支
    tags:
      - 'v*'  # 可选：在推送标签时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/${{ github.repository }}/speedtest:latest,ghcr.io/${{ github.repository }}/speedtest:${{ github.sha }}
          push: true
